SCM/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from scmapp import views

urlpatterns = [
    # path(r'^/',views.index,name='index'),
    path('scm/',include('scmapp.urls')),
    path('admin/', admin.site.urls),
]

scmapp/urls.py
from django.conf.urls import url
from scmapp import views

app_name = 'scmapp'

urlpatterns = [
    url(r'^registration',views.index),
    url(r'^user_home',views.user_home),
    url(r'^test',views.test,name='test'),
    url(r'^login_user',views.login_user,name='login_user'),

    url(r'^admin_login',views.admin_login,name='admin_login'),
    url(r'^login_admin',views.login_admin,name='login_admin'),

    url(r'^admin_home',views.admin_home,name='admin_home'),
    url(r'^user_home',views.user_home,name='user_home'),

    url(r'^user_event',views.user_event,name='user_event'),
    url(r'^ground_booking',views.ground_booking,name='ground_booking'),
    url(r'^db_ground_booking',views.db_ground_booking,name='db_ground_booking'),

    url(r'^admin_booking',views.admin_booking,name='admin_booking'),
    url(r'^admin_event',views.admin_event,name='admin_event'),

    url(r'^update_event/(?P<id>\d+)/$',views.update_event,name='update_event'),
    url(r'^db_update_event/(?P<id>\d+)/$',views.db_update_event,name='db_update_event'),
    url(r'^db_delete_event/(?P<id>\d+)/$',views.db_delete_event,name='db_delete_event'),

    url(r'^add_event',views.add_event,name='add_event'),
    url(r'^db_add_event',views.db_add_event,name='db_add_event'),

    url(r'^user_logout',views.user_logout,name='user_logout'),
    url(r'^admin_logout',views.admin_logout,name='admin_logout'),
]

templates/admin_booking.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>| Bookings</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/admin_event.css' %}">
</head>
<body>
<div class="container-fluid header text-center">
  Ground Booking
</div>

<div class="container box">
  Booking Details

  <table>
    <tr style="font-weight:500;">
      <td>No</td>
      <td>Username</td>
      <td>Date</td>
      <td>Time</td>
      <td>Mobile</td>
    </tr>

    {% for b in booking %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ b.name}}</td>
        <td>{{ b.date }}</td>
        <td>{{ b.time }}</td>
        <td>{{ b.mobile }}</td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="5" align="center">No Bookings</td>
      </tr>
    {% endfor %}


  </table>

  <div class="footer">
    <a href="{% url 'scmapp:admin_home' %}"><button>Back</button></a>
  </div>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

templates/admin_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>| Events</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/admin_event.css' %}">
</head>
<body>
<div class="container-fluid header text-center">
  Manage Events
</div>

<div class="container box">
  <a href="add_event.php"><button style="float:right;">Add Event</button></a>
  Event Details<br>
  <span style="font-size:16px;color:gray;">Click on the respective event to manage</span><br>
  <span style="font-size:16px;">{{ status }}</span>

  <table>
    <tr>
      <td>No</td>
      <td>Event name</td>
      <td>Date</td>
      <td>Time</td>
      <td>Duration</td>
      <td>Update</td>
      <td>Delete</td>
    </tr>

    {% for e in event %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ e.name}}</td>
        <td>{{ e.date }}</td>
        <td>{{ e.time }}</td>
        <td>{{ e.duration }}</td>
        <td><a href="{% url 'scmapp:update_event' id=e.eid %}">Update</a></td>
        <td><a href="{% url 'scmapp:db_delete_event' id=e.eid %}">Delete</a></td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="7" align="center">No Events</td>
      </tr>
    {% endfor %}

  </table>

  <div class="footer">
    <a href="{% url 'scmapp:admin_home' %}"><button>Back</button></a>
  </div>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

templates/admin_home.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Sports Club Management</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

<body>
<div class="container-fluid header text-center">
  Sports Club Management<br>
  Welcome {{ name }}<br>
  <a href="{% url 'scmapp:admin_logout' %}" style="font-size:20;">Logout</a>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <a href="{% url 'scmapp:admin_event' %}">
      <div class="card">
        <img src="{% static 'res/events.jpg' %}">
        <div class="card-title text-center">Events</div>
      </div>
      </a>
    </div>

    <div class="col-lg-6">
      <a href="{% url 'scmapp:admin_booking' %}">
      <div class="card">
        <img src="{% static 'res/ground.jpg' %}" style="height:312px;">
        <div class="card-title text-center">Ground Booking</div>
      </div>
      </a>
    </div>

  </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

templates/admin_login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title> | Administration</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/registration.css" %}">
  <style>
  .loginBox{
    margin:80 0 0 0;
    display:block;
  }
  </style>
</head>
<body>

<div class="container-fluid header text-center">
  Sports Club Management | Administration
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 loginBox">
      Login<br>
      <span style="font-size:18px;">{{ status }}</span>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputBox" style="font-size:18px;">
            <form action="{% url 'scmapp:login_admin' %}" method="post">
              {% csrf_token %}
              Username<br>
              <input type="text" name="name" autocomplete="off" required>

              Password<br>
              <input type="password" name="password" minlength="8" autocomplete="off" required>

              <input type="submit" value="Login" name="login" style="margin:0 25% 0 25%;">
            </form>
          </div>
        </div>
      </div>
      <!-- <a href="#" onclick="navigation(event)" id="regLink">Not a registered user? Register</a> -->

    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

templates/ground_booking.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title> | Ground Booking</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/add_event.css' %}">
</head>
<body>
<div class="container-fluid header text-center">
  Ground Booking
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box">
      Booking Details<br>
      <span style="font-size:18px">{{ status }}</span>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'scmapp:db_ground_booking' %}" method="post">
              {% csrf_token %}
              Mobile<br>
              <input type="text" name="mobile" minlength="10" maxlength="10" autocomplete="off" pattern="[6-9]{1}[0-9]{9}" title="Numbers only" required><br>

              Date<br>
              <input type="date" name="date" min="{{ date }}" autocomplete="off" required><br>

              Time<br>
              <input type="time" name="time" min="06:00" max="18:00" required>

              <div class="footer">
                <input type="reset" value="Reset" name="submit">
                <input type="submit" value="Book" name="submit">
              </div>

            </form>
          </div>
        </div>
      </div>
      <a href="{% url 'scmapp:user_home' %}">Back</a>
    </div>
  </div>
</div>

</body>
</html>

templates/registration.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Sports Club Management | Welcome</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static "css/registration.css" %}">
  <script type="text/javascript" src="{% static "js/main.js" %}"></script>
</head>
<body>

<div class="container-fluid header text-center">
  Sports Club Management
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-0 btn-bar" onclick="navigation(event)">
      <a href="#" class="myactive" id="registration">Registration</a>
      <a href="#" class="" id="login">Login</a>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box" style="display:block;">
      <!-- <span style="font-size:26px;">Registration</span> -->
      Registration<br>
      <span style="font-size:18px;">{{ status }}</span>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'scmapp:test' %}" method="post">
              {% csrf_token %}
              Username<br>
              <input type="text" name="uname" autocomplete="off" required><br>

              E-Mail<br>
              <input type="text" name="email" autocomplete="off" required><br>

              Gender<br>
              <input type="radio" name="gender" value="Male"> Male
              <input type="radio" name="gender" value="Female"> Female<br>

              Password<br>
              <input type="password" name="password" minlength="8" autocomplete="off" required><br>

              Re-enter Password<br>
              <input type="password" name="repassword" minlength="8" autocomplete="off" required>

              <input type="submit" value="Submit" name="submit" style="margin:0 25% 0 25%;">
            </form>
          </div>
        </div>
    </div>
    <a href="#" onclick="navigation(event)" id="loginLink">Already registered? Login</a>

    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 loginBox" style="display:none;">
      Login

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputBox" style="font-size:18px;">
            <form action="{% url 'scmapp:login_user' %}" method="post">
              {% csrf_token %}
              Username<br>
              <input type="text" name="name" autocomplete="off" required><br>

              Password<br>
              <input type="password" name="password" minlength="8" autocomplete="off" required>

              <input type="submit" value="Login" name="login" style="margin:0 25% 0 25%;">
            </form>
          </div>
        </div>
      </div>
      <a href="#" onclick="navigation(event)" id="regLink">Not a registered user? Register</a>

    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

templates/update_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>| Update Event</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/add_event.css' %}">
</head>
<body>
<div class="container-fluid header text-center">
  Manage Event
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box">
      Update Event

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'scmapp:db_update_event' id=event.eid %}" method="post">
              {% csrf_token %}
              Name of event<br>
              <input type="text" name="name" autocomplete="off" value="{{ event.name }}" required><br>

              Date<br>
              <input type="date" name="date" autocomplete="off" value="{{ event.date }}" required><br>

              Time<br>
              <input type="time" name="time" value="{{ event.time }}" min="06:00" max="18:00" required><br>

              Duration(hours)<br>
              <input type="number" name="duration" autocomplete="off" value="{{ event.duration }}" min="1" required>

              <div class="footer">
                <input type="reset" value="Reset" name="submit">
                <input type="submit" value="Update" name="submit">
              </div>

            </form>
          </div>
        </div>
      </div>
      <a href="{% url 'scmapp:admin_event' %}">Back</a>
    </div>
  </div>
</div>

</body>
</html>

templates/user_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>| Events</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/admin_event.css' %}">
</head>
<body>
<div class="container-fluid header text-center">
  Events
</div>

<div class="container box">
  Event Details

  <table>
    <tr>
      <td>No</td>
      <td>Event name</td>
      <td>Date</td>
      <td>Time</td>
      <td>Duration(hours)</td>
    </tr>

    {% for e in event %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ e.name}}</td>
        <td>{{ e.date }}</td>
        <td>{{ e.time }}</td>
        <td>{{ e.duration }}</td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="5" align="center">No events</td>
      </tr>
    {% endfor %}

  </table>

  <div class="footer">
    <a href="{% url 'scmapp:user_home' %}""><button>Back</button></a>
  </div>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

templates/user_home.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Sports Club Management</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

<body>
<div class="container-fluid header text-center">
  Sports Club Management<br>
  Welcome {{ name }}<br>
  <a href="{% url 'scmapp:user_logout' %}" style="font-size:20;">Logout</a><br>
  <span style="font-size:18px">{{ status }}</span>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <a href="{% url 'scmapp:user_event' %}">
      <div class="card">
        <img src="{% static 'res/events.jpg' %}">
        <div class="card-title text-center">Events</div>
      </div>
      </a>
    </div>

    <div class="col-lg-6">
      <a href="{% url 'scmapp:ground_booking' %}">
      <div class="card">
        <img src="{% static 'res/ground.jpg' %}" style="height:312px;">
        <div class="card-title text-center">Ground Booking</div>
      </div>
      </a>
    </div>

  </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>